name: Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Composer
      run: composer install --no-progress --no-suggest

    - name: Node
      run: npm install
      
    - name: Production
      run: npm run production
      
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: 'build_production'
        destination-github-username: 'Alessandro Cappellozza'
        destination-repository-name: '/'
        user-email: alessandro.cappellozza@gmail.com
      
  


